# -*- coding: utf-8 -*-
"""Data Cleaning in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WiNuVbickDY3a7USzq3WWhN0QutuH815
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = '/content/drive/MyDrive/Data Cleaning/Sample Data/sample_data.csv'
df = pd.read_csv(file_path)

df.head()

print(df.to_string())

import pandas as pd

file_path3 = '/content/drive/MyDrive/Data Cleaning/Sample Data/data.csv'
df3 =pd.read_csv(file_path3)

df3.head()

"""There is also a tail() method for viewing the last rows of the DataFrame.

The tail() method returns the headers and a specified number of rows, starting from the bottom.
"""

df3.tail()

df3.info()



"""#**Data Cleaning**

Data cleaning means fixing bad data in your data set.

Bad data could be:

* Empty cells
* Data in wrong format
* Wrong data
* Duplicates

#Empty Cells
Empty cells can potentially give you a wrong result when you analyze data.    
**1.Remove Rows**  
One way to deal with empty cells is to remove rows that contain empty cells.

This is usually OK, since data sets can be very big, and removing a few rows will not have a big impact on the result.
"""

import pandas as pd
new_df = df.dropna()
new_df.head(12)

"""**Note**: By default, the *dropna()* method returns a new DataFrame, and will not change the original.


"""

