# -*- coding: utf-8 -*-
"""Data Cleaning in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WiNuVbickDY3a7USzq3WWhN0QutuH815
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

file_path = '/content/drive/MyDrive/Data Cleaning/Sample Data/sample_data.csv'
df = pd.read_csv(file_path)

df.head()

print(df.to_string())

import pandas as pd

file_path3 = '/content/drive/MyDrive/Data Cleaning/Sample Data/data.csv'
df3 =pd.read_csv(file_path3)

